# -*- coding: utf-8 -*-
"""How2do_re_mcl_v.1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkOO2-en8nfJxLEVD2lh2XGBfvVDHYnl
"""

!pip install git+https://github.com/hilolani/re_mcl.git

from re_mcl import *
rc_mcl= load_adjmats()
print(re_mcl)
mtxlist = [rc_mcl.gadget,rc_mcl.karateclub,rc_mcl.erdosReny,rc_mcl.scalefree,rc_mcl.homophilly,rc_mcl.heterophilly]
adjacencyinfocheckedlist = [adjacencyinfocheck(i) for i in mtxlist]
adjacencylist = ['gadget', 'karateclub', 'erdosReny', 'scalefree', 'homophilly', 'heterophilly']

#Karate Club
cluslist1 = mclprocess(adjacencyinfocheckedlist[1], 20)

#Scale free graph.
cluslist = mclprocess(adjacencyinfocheckedlist[3], 20)

resultcore = branching_rmcl(cluslist,adjacencyinfocheckedlist[3],threspruning=1,reverse_process=False)
#Same as
#resultcore = rmcl_basic(cluslist,adjacencyinfocheckedlist[3],threspruning=1,reverse_process=False)

print(resultcore)

resultnoncore = rmcl_basic(cluslist,adjacencyinfocheckedlist[3],threspruning=3,reverse_process=True)

print(resultnoncore)

result_srcore = sr_mcl(cluslist,adjacencyinfocheckedlist[3])

print(result_srcore)

result_srall = sr_mcl(cluslist,adjacencyinfocheckedlist[3], coreinfoonly = False)

print(result_srall)

result_srall_dict = mcllist_to_mcldict(result_srall)

print(result_srall_dict)

mixed_result =  mixed_rmcl(cluslist, adjacencyinfocheckedlist[3], threspruning = 3.0, branching = False)

print(mixed_result)

mixed_result_dict = mcllist_to_mcldict(mixed_result)

print(mixed_result_dict)

