# -*- coding: utf-8 -*-
"""re_mcl_demo_Colab.ipynb
Automatically generated by Colab.
"""

!pip install git+https://github.com/hilolani/re_mcl.git

from re_mcl import *
re_mcl= load_adjmats()
mtxlist = [re_mcl.gadget,re_mcl.karateclub,re_mcl.erdosReny,re_mcl.scalefree,re_mcl.homophilly,re_mcl.heterophilly,re_mcl.eat]
[adjacencyinfocheck(i) for i in mtxlist]

mclprocess(re_mcl.karateclub)

cluslist = mclprocess(re_mcl.scalefree, 20)
rmcl_basic(cluslist,re_mcl.scalefree)#The core cluster is divided based on the algorithm of RMCL.

