# -*- coding: utf-8 -*-
"""re_mcl_demo_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhiWdciCKN8CxRbw8yVvmoce32g77Xkb
"""

!pip install git+https://github.com/hilolani/re_mcl.git

from re_mcl import *

re_mcl= load_adjmats()

print(re_mcl.gadget)
print(re_mcl.karateclub)
print(re_mcl.erdosReny)
print(re_mcl.scalefree)
print(re_mcl.homophilly)
print(re_mcl.heterophilly)

mtxlist = [re_mcl.gadget,re_mcl.karateclub,re_mcl.erdosReny,re_mcl.scalefree,re_mcl.homophilly,re_mcl.heterophilly]
[adjanceyinfocheck(i) for i in mtxlist]

mclprocess(re_mcl.karateclub)

!cat mcl_results.log

